using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Windows.Forms;
using SimpleKVM.Displays;
using System.Linq;
using SimpleKVM.Rules.Actions;
using SimpleKVM.GUI.Actions;
using IAction = SimpleKVM.Rules.Actions.IAction;
using SimpleKVM.Configuration;

namespace SimpleKVM.GUI
{
    public partial class UcSelectMonitorSource : UserControl, IValidate, IActionCreator
    {
        public UcSelectMonitorSource()
        {
            InitializeComponent();

            Controls
                .OfType<Label>()
                .ToList()
                .ForEach(label =>
                {
                    label.MouseClick += (s, e) =>
                    {
                        OnMouseClick(e);
                    };
                });
        }

        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Monitor? Monitor { get; protected set; }
        int OriginalSourceId;

        public void DisplayMonitor(string autogeneratedName, Monitor monitor, int sourceIdToSelect)
        {
            Monitor = monitor;
            OriginalSourceId = sourceIdToSelect;

            lblMonitorName.Text = autogeneratedName;

            //var tooltip = new ToolTip();
            //tooltip.SetToolTip(lblMonitorName, monitor.MonitorUniqueId);

            var currentSource = monitor.GetCurrentSource();

            var monitorItems = monitor
                                    .ValidSources
                                    .Select(source =>
                                    {
                                        var sourceName = source.SourceName;

                                        if (source.SourceId == currentSource)
                                        {
                                            sourceName += " (Active)";
                                        }

                                        return new
                                        {
                                            SourceName = sourceName,
                                            source.SourceId
                                        };
                                    })
                                    .ToList();

            monitorItems.Add(new
            {
                SourceName = "Leave unchanged",
                SourceId = -1
            });

            cmbSources.DisplayMember = "SourceName";
            cmbSources.ValueMember = "SourceId";
            cmbSources.DataSource = monitorItems;

            cmbSources.SelectedIndex = monitorItems
                                        .Select((monitorItem, index) => new
                                        {
                                            MonitorItem = monitorItem,
                                            Index = index
                                        })
                                        .FirstOrDefault(monitorItem => monitorItem.MonitorItem.SourceId == sourceIdToSelect)
                                        ?.Index ?? 0;
        }

        public static string SourceIdToName(int sourceId)
        {
            return Displays.VcpSourceNames.SourceIdToName(sourceId);
        }

        public List<IAction> GetAction()
        {
            var result = new List<IAction>();
            if (Monitor != null)
            {
                var selectedSourceId = (cmbSources.SelectedValue as int?) ?? OriginalSourceId;

                var newAction = new SetMonitorSourceAction(Monitor, selectedSourceId);
                result.Add(newAction);
            }

            return result;
        }

        public List<ValidationResult> ValidateData()
        {
            var result = new List<ValidationResult>();
            return result;
        }
    }
}
